spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: rabbitmq-queue
  exchange:
    name: rabbitmq-exchange
  routing:
    key: rabbitmq-routing-key
